name = "vainilla"
author = "ImUrX, Kodi"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a9f523f90e18c3a163dbcf5924302ef892cd61c28be2af8273e78f41a7d511f"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
