name = "vainilla"
author = "ImUrX, Kodi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a0084597662ce40c58c0307f611ae5525f685b4b66ae35ffd7ecfe925e33d8b"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
