name = "vainilla"
author = "ImUrX, Kodi, Kibo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1487bb3f4ba20fde7d4023bd94a49e11f06a92c248b60e08fbad07da77dc689"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
