name = "vainilla"
author = "ImUrX, Kodi"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1368ab7a4e704533bee8f84f6c3220ae6b2809770f0c11738eb9f1986c66b577"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
