name = "vainilla"
author = "ImUrX, Kodi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a64181324c713e2c475498e2591e0225edca37f1ed55cfa3f17832a1b26c3379"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
