name = "vainilla"
author = "ImUrX, Kodi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "836b6ee67dad5709ccb6d049a4999d22b0a8bdada9c6aa565b36b406d8a7ad72"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
