name = "vainilla"
author = "ImUrX, Kodi"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "731059ae774d6bb3109480466d71589806aebd95f10016f7ddeffbfb85f4b211"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
