name = "vainilla"
author = "ImUrX, Kodi"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee60e98b5c6f98c66c1c818d78891891c0198af2949b6f2aadfc59e42c86a0f1"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
