name = "vainilla"
author = "ImUrX, Kodi, Kibo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c77e9b9c7ab2c567e99bee784677295adbbd64d964e5c0c3c91851f620f299fa"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
