name = "vainilla"
author = "ImUrX, Kodi"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "985e33f13350975f7a242d454128c0b8d3d6118e65341858966b709d4fda79d0"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
