name = "vainilla"
author = "ImUrX, Kodi"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7037a2995da7fab577a8955e4ac83e8b63f5963853341d5b883df0bc59940458"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
