name = "vainilla"
author = "ImUrX, Kodi, Kibo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c554e430e059ff82bc6eea2f707159e6c928dd14fb62a1c6d7437d46ecceedb4"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
