name = "vainilla"
author = "ImUrX, Kodi, Kibo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b905640b9480d41754dc6120a63eac43197e30819eb6390905b63816899cb59c"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
