name = "vainilla"
author = "ImUrX, Kodi"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c06d56d8ea19dca7ea2e92bd4302efa9f940562834de61051dce98c65f806b21"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
