name = "vainilla"
author = "ImUrX, Kodi"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15cb838afa9dfef2d5e0ee9ddc38dea8747a74f268552403c9e29757a0073b2b"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
