name = "vainilla"
author = "ImUrX, Kodi, Kibo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47598197758171128b286c5ae9c662c33b03ce9daa06c66897df6fa9f27782ad"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
