name = "vainilla"
author = "ImUrX, Kodi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65bfb3c1106944527f8408f9ba254630154c24db718fcb8360a8f51c4873ad14"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
