name = "vainilla"
author = "ImUrX, Kodi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de319f600df7fe746e047a40124e2cd3f525cc574c9fdc0ff9a7e5e4c0a826f4"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
