name = "vainilla"
author = "ImUrX, Kodi"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9984c8a9d1718ceb1e4e2fcb4c4c91b4048f8c3393c2dc08a34caf97ce744b2b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
