name = "vainilla"
author = "ImUrX, Kodi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b73b9f6222f3b64e03a5ad0eab34e4577e4a94b2d80a4eafe1537d07ef5095cf"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"

[options]
acceptable-game-versions = ["1.20.4", "1.20.5"]
