name = "vainilla"
author = "ImUrX, Kodi"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0dd59114d5e4df3f3f8b3111c5233e0516b4099fb74bf705929a588398a11a3"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
