name = "vainilla"
author = "ImUrX, Kodi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3853d0a008c3e9823b4551e059d62e39e358410e6997a7f0eeb930b1c83aff3e"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
