name = "vainilla"
author = "ImUrX, Kodi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "660145f0406910bd9876d8d6d177b25bee3eb24890a3c693924e20e7c5c218ad"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"

[options]
acceptable-game-versions = ["1.20.4", "1.20.5"]
